// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// allocate
NumericVector allocate(double flow, NumericVector pref_v, NumericVector soc_v, NumericVector cap_v);
RcppExport SEXP eflows_allocate(SEXP flowSEXP, SEXP pref_vSEXP, SEXP soc_vSEXP, SEXP cap_vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type flow(flowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pref_v(pref_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type soc_v(soc_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cap_v(cap_vSEXP);
    rcpp_result_gen = Rcpp::wrap(allocate(flow, pref_v, soc_v, cap_v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"eflows_allocate", (DL_FUNC) &eflows_allocate, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_eflows(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
