# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allocate <- function(flow, pref_v, soc_v, cap_v) {
    .Call('eflows_allocate', PACKAGE = 'eflows', flow, pref_v, soc_v, cap_v)
}

