# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

appreciate <- function(vector, self_discharge, eff, backwards) {
    .Call('_eflows_appreciate', PACKAGE = 'eflows', vector, self_discharge, eff, backwards)
}

depreciate <- function(vector, self_discharge, eff, backwards) {
    .Call('_eflows_depreciate', PACKAGE = 'eflows', vector, self_discharge, eff, backwards)
}

fct_chop <- function(vector, n_pieces) {
    .Call('_eflows_fct_chop', PACKAGE = 'eflows', vector, n_pieces)
}

backshiftCpp <- function(consumption, self_discharge, eff, horizon) {
    .Call('_eflows_backshiftCpp', PACKAGE = 'eflows', consumption, self_discharge, eff, horizon)
}

distributeCpp <- function(flow, soc, vol, share = as.numeric( c(1)), level = as.numeric( c(1)), active = as.logical( c(1)), eff = as.numeric( c(1)), cap = as.numeric( c(0))) {
    .Call('_eflows_distributeCpp', PACKAGE = 'eflows', flow, soc, vol, share, level, active, eff, cap)
}

formatFlexSteps <- function(matrix, flex_step, max_step = -1L) {
    .Call('_eflows_formatFlexSteps', PACKAGE = 'eflows', matrix, flex_step, max_step)
}

divideInChunks <- function(x, precision) {
    .Call('_eflows_divideInChunks', PACKAGE = 'eflows', x, precision)
}

whichMin <- function(x) {
    .Call('_eflows_whichMin', PACKAGE = 'eflows', x)
}

sliceCurrent <- function(vec, start, end) {
    .Call('_eflows_sliceCurrent', PACKAGE = 'eflows', vec, start, end)
}

envCurrent <- function(input, out, start, span) {
    .Call('_eflows_envCurrent', PACKAGE = 'eflows', input, out, start, span)
}

listToCube <- function(mtx_list) {
    .Call('_eflows_listToCube', PACKAGE = 'eflows', mtx_list)
}

cubeToList <- function(xcube) {
    .Call('_eflows_cubeToList', PACKAGE = 'eflows', xcube)
}

foreShiftCpp <- function(mtx_list, cap_charge, env_fit, call_fit, env_aux, call_aux) {
    .Call('_eflows_foreShiftCpp', PACKAGE = 'eflows', mtx_list, cap_charge, env_fit, call_fit, env_aux, call_aux)
}

